"""
Test to verify that hashtags are actually included in the final output.

This test checks:
1. That hashtags are generated by text_generator
2. That hashtags are included in the final formatted output
3. That hashtags appear in the text/caption for all platforms
"""

import unittest
import os
import sys
from unittest.mock import Mock, patch, MagicMock

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))


class TestHashtagOutput(unittest.TestCase):
    """Test that hashtags are included in final output."""

    def setUp(self):
        """Set up test fixtures."""
        # Mock environment to avoid needing actual model
        os.environ['PEFT_ADAPTER_PATH'] = '/fake/path'  # Will fall back to HTTP mode
        
    def test_text_generator_ensures_hashtags(self):
        """Test that text_generator._ensure_hashtags generates hashtags."""
        from agents.content_creator.text_generator import TextGenerator
        
        # Create generator (will fail to load model, but we can test hashtag logic)
        try:
            gen = TextGenerator()
        except (ValueError, Exception):
            # If initialization fails, create a minimal mock
            gen = Mock()
            gen._ensure_hashtags = TextGenerator._ensure_hashtags.__get__(gen, TextGenerator)
        
        # Test hashtag generation for each domain
        test_cases = [
            ({"trend": {"title": "foreclosure help", "domain": "Foreclosures"}}, "twitter", ["#ForeclosureSupport", "#Homeowners"]),
            ({"trend": {"title": "trading futures", "domain": "Trading Futures"}}, "twitter", ["#FuturesTrading", "#RiskManagement"]),
            ({"trend": {"title": "assisted living", "domain": "Assisted Living"}}, "twitter", ["#AssistedLiving", "#Caregiving"]),
        ]
        
        for context, platform, expected_prefixes in test_cases:
            hashtags = gen._ensure_hashtags(context, platform)
            self.assertGreater(len(hashtags), 0, f"Should generate hashtags for {platform} with {context['trend']['domain']}")
            # Check that hashtags start with #
            for tag in hashtags:
                self.assertTrue(tag.startswith("#"), f"Hashtag {tag} should start with #")
            # Check platform limits (Twitter max 2)
            if platform == "twitter":
                self.assertLessEqual(len(hashtags), 2, "Twitter should have max 2 hashtags")

    def test_hashtags_in_text_generator_output(self):
        """Test that hashtags are included in text_generator output structure."""
        from agents.content_creator.text_generator import TextGenerator
        
        # Check the generate_text method structure
        # The method should return hashtags in the result dict
        # Line 172: "hashtags": [t.lstrip("#") for t in tags]
        # Line 167: final_text = final_text.rstrip() + "\n\n" + " ".join(tags)
        
        # Verify the code structure includes hashtags
        import inspect
        from agents.content_creator import text_generator
        
        source = inspect.getsource(text_generator.TextGenerator.generate_text)
        
        # Check that hashtags are added to text
        self.assertIn("_ensure_hashtags", source, "generate_text should call _ensure_hashtags")
        self.assertIn("hashtags", source, "generate_text should include hashtags in result")
        self.assertIn("final_text", source, "generate_text should add hashtags to final_text")

    def test_content_creator_adds_hashtags(self):
        """Test that content_creator_agent adds hashtags to output."""
        from agents.content_creator.content_creator_agent import ContentCreatorAgent
        
        # Check the code structure
        import inspect
        from agents.content_creator import content_creator_agent
        
        source = inspect.getsource(content_creator_agent.ContentCreatorAgent.generate_content_for_platform)
        
        # Verify hashtags are handled
        self.assertIn("hashtags", source, "generate_content_for_platform should handle hashtags")
        self.assertIn("hashtag_text", source, "Should create hashtag_text for appending")
        
        # Check that twitter and instagram get hashtags appended
        self.assertIn("twitter", source.lower(), "Should handle twitter platform")
        self.assertIn("instagram", source.lower(), "Should handle instagram platform")

    def test_hashtag_flow_analysis(self):
        """Analyze the complete hashtag flow through the system."""
        print("\n=== HASHTAG FLOW ANALYSIS ===")
        
        print("\n1. TextGenerator.generate_text():")
        print("   - Calls _ensure_hashtags() to generate hashtags")
        print("   - Adds hashtags to final_text: final_text + '\\n\\n' + ' '.join(tags)")
        print("   - Returns dict with 'hashtags' field: [t.lstrip('#') for t in tags]")
        print("   - Returns dict with 'text' field: final_text (includes hashtags)")
        
        print("\n2. ContentCreatorAgent.generate_content_for_platform():")
        print("   - Gets hashtags from trend_data.get('hashtags', [])")
        print("   - For TWITTER: Appends hashtags to formatted_content['text']")
        print("   - For INSTAGRAM: Appends hashtags to formatted_content['caption']")
        print("   - For LINKEDIN/FACEBOOK: Hashtags in dict but NOT appended to text")
        
        print("\n3. POTENTIAL ISSUES:")
        print("   - LinkedIn and Facebook hashtags are NOT appended to text")
        print("   - They're only in the 'hashtags' field of the dict")
        print("   - Twitter/Instagram get hashtags appended TWICE (once in text_generator, once in content_creator)")
        
        print("\n4. VERIFICATION NEEDED:")
        print("   - Check if LinkedIn/Facebook posts actually show hashtags")
        print("   - Check if Twitter/Instagram have duplicate hashtags")
        
        # This test always passes - it's informational
        self.assertTrue(True, "Flow analysis completed")

    def test_platform_hashtag_coverage(self):
        """Test that all platforms can receive hashtags."""
        print("\n=== PLATFORM HASHTAG COVERAGE ===")
        
        platforms = ["twitter", "instagram", "linkedin", "facebook"]
        
        print("\nPlatform hashtag handling:")
        for platform in platforms:
            if platform in ["twitter", "instagram"]:
                print(f"  {platform}: Hashtags appended to text/caption [OK]")
            else:
                print(f"  {platform}: Hashtags in dict only (NOT appended to text) [WARN]")
        
        print("\nRECOMMENDATION:")
        print("  - Ensure LinkedIn and Facebook also append hashtags to text")
        print("  - Or verify that the platform formatter handles hashtags separately")
        
        # This test always passes - it's informational
        self.assertTrue(True, "Coverage analysis completed")


if __name__ == '__main__':
    unittest.main(verbosity=2)
